### ISSUE TITLE
请问一下，可以不依托于华为电脑管家而是微软商店的Huawei pen吗

### ISSUE THREAD

**Issue by luoquan-30** [eiyooooo/MateBook-E-Pen#4]
rt，因为手上的板子是matebook e go，用电脑管家只能转译太耗资源，所以想看看能不能利用这个APP
https://apps.microsoft.com/detail/huaweipenapp/9PL42N8RRXJN?cid=CorelSite&hl=zh-cn&gl=cn

**Comment by eiyooooo** [comment]
> rt，因为手上的板子是matebook e go，用电脑管家只能转译太耗资源，所以想看看能不能利用这个APP https://apps.microsoft.com/detail/huaweipenapp/9PL42N8RRXJN?cid=CorelSite&hl=zh-cn&gl=cn

[PenService.zip](https://github.com/eiyooooo/MateBook-E-Pen/files/13530011/PenService.zip)
需将此zip解压得到的PenService.dll
放在
C:/Program Files/Huawei/HuaweiPen/PenService.dll
或
C:/Program Files/Huawei/PCManager/components/accessories_center/accessories_app/AccessoryApp/Lib/Plugins/Depend/PenService.dll

**Comment by luoquan-30** [comment]
> > rt，因为手上的板子是matebook e go，用电脑管家只能转译太耗资源，所以想看看能不能利用这个APP https://apps.microsoft.com/detail/huaweipenapp/9PL42N8RRXJN?cid=CorelSite&hl=zh-cn&gl=cn
> 
> 这软件是不需要打开电脑管家的 但是我手上只有matebook e，这软件是按照matebook e的驱动来设计的 e go没有测试过能不能正常运行 你可以下载下来试试

尝试过卸载华为电脑管家，但是奇怪的是，卸载完以后就不能使用了，所以你提到的不依托应该是指不需要后台运行，但是可能依旧调用了和笔有关的相关驱动

**Comment by luoquan-30** [comment]
> > rt，因为手上的板子是matebook e go，用电脑管家只能转译太耗资源，所以想看看能不能利用这个APP https://apps.microsoft.com/detail/huaweipenapp/9PL42N8RRXJN?cid=CorelSite&hl=zh-cn&gl=cn
> 
> [PenService.zip](https://github.com/eiyooooo/MateBook-E-Pen/files/13530011/PenService.zip) 需将此zip解压得到的PenService.dll 放在 C:/Program Files/Huawei/HuaweiPen/PenService.dll 或 C:/Program Files/Huawei/PCManager/components/accessories_center/accessories_app/AccessoryApp/Lib/Plugins/Depend/PenService.dll

事实上，当我卸载完电脑管家以后，这两个文件夹就都没了，所以我才想尝试询问一下，是否可以通过此软件来实现。当然，最好的办法是可以完全独立（，十分感谢你对我的帮助，同时希望可以有一个arm64的版本，无论如何，转译运行还是会影响性能的。

**Comment by eiyooooo** [comment]
https://github.com/eiyooooo/MateBook-E-Pen/releases/tag/v2.1.1
v2.1.1版本可在不安装华为电脑管家的情况下运行
另外由于PenService.dll没有ARM64的版本，故无法编译ARM64版本

**Comment by awarson2233** [comment]
实测将双击功能映射至截图功能，即可在不启动任何华为服务的情况下使用该插件

**Comment by dantmnf** [comment]
> 另外由于PenService.dll没有ARM64的版本，故无法编译ARM64版本

编译 ARM64EC 版本，可以载入 x64 dll

**Comment by eiyooooo** [comment]
> > 另外由于PenService.dll没有ARM64的版本，故无法编译ARM64版本
> 
> 编译 ARM64EC 版本，可以载入 x64 dll

已更新 ARM64EC 版本
https://github.com/eiyooooo/MateBook-E-Pen/releases/download/v2.1.1/MateBook-E-Pen.ARM64EC.exe
