### ISSUE TITLE
Onenote 2310版全屏模式无法正常切换

### ISSUE THREAD

**Issue by zyqyq** [eiyooooo/MateBook-E-Pen#6]
对于onenote2310版，若在非全屏模式完成控件捕获，则进入全屏后无法正常完成切换，显示未捕获控件并要求重新捕获；若在全屏模式下完成捕获，则非全屏模式则无法正常切换。从更新历史中看到已经适配了onenote for win10的全屏模式（好似还有上次使用的笔的记忆功能），不知道能不能类似的给普通版本的OneNote做一下适配呢。
![image](https://github.com/eiyooooo/MateBook-E-Pen/assets/53159652/f230c39f-a8fe-4927-9719-ca9710cbb057)

**Comment by eiyooooo** [comment]
固定一个窗口模式使用即可，避免页面结构改变，之前测试的时候发现Onenote不同版本不同情况下页面结构好像不一样，单独适配比较困难，故使用捕获功能是目前较好的解决方案

**Comment by zyqyq** [comment]
好哒，谢谢大佬啦！大佬的方案是我目前用过来体验最好的双击功能的替换方案了呢。等我代码水平再精进一些了有空我尝试研究一下源代码自己修改吧

**Comment by eiyooooo** [comment]
这个软件写的时候我没啥水平，架构比较粗糙 :grin:
